global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-message-producer"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["172.17.0.1:8080"] # 172.17.0.1 eh o ip do host.docker.internal
        labels:
          application: "api-message-producer"